### ISSUE TITLE
Installation Failed When Installing Python for Android

### ISSUE THREAD

**Issue by foxtrotmike** [kuri65536/python-for-android#93] opened 2015-05-05 17:02 UTC
* What device(s) are you experiencing the problem on?
  * Nexus 7
* What OS version are you running on the device?
  * Android 5.1
* What version of the product are you using?
  * SL4A r6 (sl4a-r6x04-arm-debug.apk)
  * Python for android - debug (apk file available at https://github.com/kuri65536/python-for-android/releases/download/r21/PythonForAndroid-debug.apk). I couldn't find other apks for later versions.
* What steps will reproduce the problem?
  1. Install SL4A
  2. Install Python for Android
  3. Press Install after launching Python for Android
* What is the expected output? What do you see instead?
  * expected: Installing Python Successfuly
  * see: "Installation Failed" toast
* Please provide any additional information below.
Is there a way of installing Python without pressing "Install" in the python for android app after downloading all the relevant folders/apps?

**Comment by kuri65536** [comment] 2015-05-07 21:13
Thank you for your report.
It was caused by my mistake...and fixed in latest commit: https://github.com/kuri65536/python-for-android/commit/fb9146451dce18fe861dbf94cae2512cf9066938

**Closed by kuri65536** 2015-05-07 21:13 UTC
